### PR TITLE
Add different colour for passive votes

### LINKED ISSUE #1: Color active votes in different shade of blue
Currently both _passive_ and _active_ votes are colored blue in the vote table (see https://bip100.tech). 

_Passive_ meaning that there is no vote in the coinbase, thus the vote defaults to current limit. _Active_ meaning that there is a vote in the coinbase, such as bitcoin.com currently voting for 8MB with _/EB8/_.

We should have a different shade of blue for blocks with an active vote to visualize how many miners are voting.

@chaintip 365 days

### PR DESCRIPTION
**Pull request by DJMcNab**
Additionally, removes a surplus semicolon from python script
Switch to using bootstrap background colours
Refactor index script slightly - remove missing var statements and only loop through votes once.

@chaintip fixes #1

### CODE REVIEW

**Review by dagurval — APPROVED** [review]

**Comment by dagurval** [comment]
This look awesome! Thanks for doing this enhancement, and also for taking the time to improve the code in general.

I'll merge this as soon as I get confirmation that chaintip is working (https://github.com/chaintip/chaintip-github/issues/32)

**Comment by DJMcNab** [comment]
Is changing the url in `fetch` to 'https://bip100.tech/period/' OK. I only did it for testing purposes, but I don't think there's any reason it shouldn't be?

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#1](http://github.chaintip.org/dagurval/bip100.tech/issues/1) first, @DJMcNab will claim the `0.01608291 BCH`| `~  13.46 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/28) and all future tips to the issue.

**Comment by chaintip** [comment]
Nice work @DJMcNab! Your pull request has been merged and the [bounty](http://github.chaintip.org/chaintip/bounties/issues/28) of `0.01608291 BCH`| `~  14.38 USD` has been sent to your wallet.

**Comment by dagurval** [comment]
> Is changing the url in fetch to 'https://bip100.tech/period/' OK. I only did it for testing purposes, but I don't think there's any reason it shouldn't be?

It gets real confusing if you're testing it out on a local node.

Your PR is now live on https://bip100.tech, thanks!

**Comment by DJMcNab** [comment]
No problem. I did forget about testing it with a local node. (I only tested using the live data)

I'm glad I found the project, it's an interesting website and technology.

**Comment by dgenr8** [comment]
Thanks @DJMcNab!

**Pull request merged**
